import { z } from "zod"

export const HookNameSchema = z.enum([
  "context-window-monitor",
  "session-recovery",
  "session-notification",
  "comment-checker",
  "tool-output-truncator",
  "question-label-truncator",
  "directory-agents-injector",
  "directory-readme-injector",
  "empty-task-response-detector",
  "think-mode",
  "model-fallback",
  "anthropic-context-window-limit-recovery",
  "preemptive-compaction",
  "rules-injector",
  "background-notification",
  "auto-update-checker",
  "keyword-detector",
  "agent-usage-reminder",
  "non-interactive-env",
  "interactive-bash-session",

  "thinking-block-validator",
  "tool-pair-validator",
  "compaction-context-injector",
  "compaction-todo-preserver",
  "claude-code-hooks",
  "edit-error-recovery",
  "json-error-recovery",
  "delegate-task-retry",
  "sisyphus-junior-notepad",
  "no-sisyphus-gpt",
  "unstable-agent-babysitter",
  "task-resume-info",
  "tasks-todowrite-disabler",
  "write-existing-file-guard",
  "bash-file-read-guard",
  "anthropic-effort",
  "hashline-read-enhancer",
  "read-image-resizer",
  "todo-description-override",
  "webfetch-redirect-guard",
  "legacy-plugin-toast",
])

export type HookName = z.infer<typeof HookNameSchema>
